Linux update

diff --git a/runcoms/zshenv b/runcoms/zshenv
--- a/runcoms/zshenv
+++ b/runcoms/zshenv
@@ -1,10 +1,3 @@
-#
-# Defines environment variables.
-#
-# Authors:
-#   Sorin Ionescu <sorin.ionescu@gmail.com>
-#
-
 # Ensure that a non-login, non-interactive shell has a defined environment.
 if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
   source "${ZDOTDIR:-$HOME}/.zprofile"
@@ -14,48 +7,29 @@ fi
 
 # .zshenv created by Kevin Song for use on OS X and Linux
 
-# Check our OS Type
-OSNAME="unknown"
-case $OSTYPE in 
-    darwin*)
-        OSNAME="osx"
-        ;;
-    linux*)
-        OSNAME="linux"
-        ;;
-    *bsd*)
-        OSNAME="bsd"
-        ;;
-esac
+# Initialize OPAM environment for OCaml
+. /home/chipbuster/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true
 
-PATH=~/.cabal/bin:$PATH            #Mostly for cabal
-PATH=$PATH:~/.cabal/bin            #PATH for personal cabal
-PATH=$PATH:~/.gem/ruby/2.0.0/bin   #PATH for RubyGems (e.g. grunt)
+# Define a function to use xdg-open and alias it (simiar to OS X)
+function open-xdg-thing(){
+  xdg-open "$1" &> /dev/null || printf "xdg-open could not open %s (maybe bad mimetype?)\n" "$1"
+}
+alias open="open-xdg-thing"
+
+# Command-not-found suggestions from pkgfile
+source /usr/share/doc/pkgfile/command-not-found.zsh
+
+PATH=$PATH:~/.cabal/bin:~/.local/bin #for Cabal and Stack
+PATH=$PATH:~/.gem/ruby/2.3.0/bin   #PATH for RubyGems (e.g. grunt)
+PATH=$PATH:/opt/cvc/bin            #PATH for texmol/volrover/f2dock + co.
+PATH=$PATH:/opt/script
+
+#Export important variables
 export MANPATH=/opt/local/share/man:$MANPATH
 export EDITOR=vim
-
-if [ "$OSNAME" = "osx" ]; then
-    #Make sure clang knows about our libraries from MacPorts
-    export LIBRARY_PATH=$LIBRARY_PATH:/opt/local/lib
-    PATH=/opt/custom/bin:/opt/custom/sbin:$PATH #Path for manual installs
-    PATH=/opt/local/bin:/opt/local/sbin/:$PATH #Path for MacPorts
-
-    #Add rudimentary history to sftp on OS X
-    alias sftp="rlwrap sftp"
-
-    #Rebind text tools to their GNU variants
-    alias awk=gawk
-    alias sed=gsed
-    alias diff=gdiff
-  
-elif [ "$OSNAME" = "linux" ]; then
-    #Do some linuxy-things
-  
-elif [ "$OSNAME" = "bsd" ]; then
-    #Do some BSD things
-  
-else
-    echo "Warning: could not deduce OS type from \$OSTYPE"
-fi
-
+export VISUAL=vim
 export PATH
+
+### ENVIRONMENTAL NAMES
+VOLROVSRC="/home/chipbuster/Spinny/CVC/svn/github/VolRoverN"
+SKATSRC="/home/chipbuster/Spinny/CVC/skull-atlas"
